
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Trigger Jenkins Job

on:
  workflow_dispatch:

jobs:
  jenkins-run-job-with-output:
    outputs:
      jenkins_output: ${{ steps.jenkins-job.outputs.jenkins_output }}
    steps:
      - id: jenkins-job
        name: Run Jenkins Job
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          url: https://product-team.saas-preprod.beescloud.com/
          username: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_PASSWORD }}
          job-name: JenkinsBuild

      - id: expose-output
        name: Expose Jenkins Job Output
        uses: docker://exozet/jq:1.6-r0
        run: |
          echo "Artifact Name: ${{ fromJSON(steps.jenkins-job.outputs.jenkins_output).artifactName }}"
          echo "Version: ${{ fromJSON(steps.jenkins-job.outputs.jenkins_output).version }}"

  register-build-artifact:
    needs: [jenkins-run-job-with-output]
    steps:
      - name: register-build-artifacts
        uses: https://github.com/cloudbees-io/register-build-artifact@v1
        with:
          name: ${{ fromJSON(needs.jenkins-run-job-with-output.outputs.jenkins_output).artifactName }}
          version: ${{ fromJSON(needs.jenkins-run-job-with-output.outputs.jenkins_output).version }}
          url: ${{ fromJSON(needs.jenkins-run-job-with-output.outputs.jenkins_output).url }}
          digest: ${{ fromJSON(needs.jenkins-run-job-with-output.outputs.jenkins_output).digest }}
         
